### ISSUE TITLE
[DEPR]: Remove CTA

### ISSUE THREAD

**Issue by asadali145** [openedx/frontend-app-ora-grading#360]
### Proposal Date

2024-10-01

### Target Ticket Acceptance Date

2024-10-15

### Earliest Open edX Named Release Without This Functionality

Teak - 2025-04

### Rationale

CTA was added 2 years ago and it has served the purpose. We can safely remove it.

CTA is always visible and there is no way to hide/disable it.

### Removal

The following will be removed:

- [CTA](https://github.com/openedx/frontend-app-ora-grading/tree/master/src/containers/CTA) and respective usage.

### Replacement

None

**Comment by awais-ansari** [comment]
@asadali145, We are still using the Notifications banner to inform learners about newly available ORA-related notification preferences. Thanks

**Comment by asadali145** [comment]
Thanks @awais-ansari, I have updated the ticket to remove the CTA.

**Comment by asadali145** [comment]
@brian-smith-tcril Did you get a chance to look into this DEPR ticket?

**Comment by brian-smith-tcril** [comment]
We're going to remove this because we shouldn't have links to org specific resources (in this case a google form) in the platform. 
@awais-ansari If this functionality is needed a [`frontend-plugin-framework`](https://github.com/openedx/frontend-plugin-framework/) slot should be added and the banners can be created as plugins that can be put into the slot.

**Comment by feanil** [comment]
This was completed via https://github.com/openedx/frontend-app-ora-grading/pull/347
